name: Add comment
on:
  workflow_run:
    types:
      - 'completed'
    workflows:
      - 'PR Checks'

jobs:
  add-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Add comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: 22
          body: test body
          edit-mode: replace
