name: End-to-End Tests
on:
  pull_request_review: 
    types: [submitted]  

concurrency:
  group: ${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  test-e2e:
    if: ${{ contains(github.event.review.body, '/test') }}
    timeout-minutes: 15
    name: E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: React to comment
        continue-on-error: true
        run: |
          gh api --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${{ github.repository }}/pulls/comments/${{ github.event.review.id }}/reactions \
           -f "content=+1"
        env:
          GH_TOKEN: ${{ github.token }}
  
      - uses: actions/checkout@v4

      - run: git status
      - run: 'echo running e2e tests'
