name: End-to-End Tests
on:
  pull_request_review: 
    types: [submitted]  

concurrency:
  group: ${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  test-e2e:
    if: ${{ contains(github.event.review.body, '/test') }}
    timeout-minutes: 15
    name: E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: React to comment
        uses: peter-evans/create-or-update-comment@v4
        continue-on-error: true
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-id: ${{ github.event.review.id }}
          reactions: '+1'
          reactions-edit-mode: replace

      - uses: actions/checkout@v4

      - run: git status
      - run: 'echo running e2e tests'
