name: Nightly build

# should be a cron
on:
  push:
    branches: [main]

permissions:
  contents: write

defaults:
  run:
    shell: bash

jobs:
  build-nightly:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version-file: ".nvmrc" }
      - name: Define version
        id: version
        run: |
          VERSION=$(date +%Y.%m.%d)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "VERSION_NAME=Nightly $VERSION" >> $GITHUB_OUTPUT
      - name: Build
        run: |
          ./scripts/build.sh ${{ steps.version.outputs.VERSION }} nightly chrome
          ./scripts/build.sh ${{ steps.version.outputs.VERSION }} nightly firefox
        #   - name: Delete existing release
        #     # https://cli.github.com/manual/gh_release_delete
        #     run: gh release delete nightly --cleanup-tag --yes
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/chrome.zip
            dist/firefox.zip
          target_commitish: ${{ github.sha }}
          tag_name: "nightly"
          name: Nightly ${{ steps.version.outputs.VERSION }}
          prerelease: true
